#ci.yml vérifie ton code automatiquement
#pipeline -> tu envoies ton code → GitHub lance automatiquement des étapes → vérifie si tout marche
name: CI
on:
  push:
    branches: [main, dev]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          node-version: 20 
      - run: npm install  
      - run: npm run build || echo "no build"
      - run: npm test || echo "no tests"
      - run: npm run lint || echo "no lint"